#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import py_trees_ros_tutorials
import rclpy

behaviour = py_trees_ros_tutorials.behaviours.ScanContext(
    name="ContextSwitch"
)

rclpy.init()

node = rclpy.create_node("scan_context")

behaviour.setup(node=node)
behaviour.initialise()

rclpy.shutdown()
